config/routes.rb
LeagueManager::Application.routes.draw do
  
  devise_for :users

  devise_scope :user do
  	get 'sign_up' => 'devise/sessions#new'
  end

  root :to => 'seasons#index'
  
  resources :timeslots
  
  resources :matches

  resources :teams
  
  
  get 'home' => 'home#index'
  
  get 'sched' => 'matches#index'
  
  get 'standings' => 'teams#index'
  
  get 'contacts' => 'home#contact'
    
  
#   delete 'lines/:id', :controller => 'lines', :action => 'destroy', :as => 'train_line'
  
  put 'seasons/:id' => 'seasons#update'
  
  get 'seasons/:id/edit' => 'seasons#edit', :as => 'edit_season'
  
  post 'seasons' => 'seasons#create', :as => 'seasons'
  
  get 'seasons/new' => 'seasons#new', :as => 'new_season'
  
  get 'seasons' => 'seasons#index'
  
  get 'seasons/:id' => 'seasons#show', :as => 'season'
  
  put 'seasons/:season_id/season_teams/:id' => 'season_teams#update', :as => 'season_team'
  
  get 'seasons/:id/standings' => 'season_teams#standing', :as => 'standings'
  
  get 'seasons/:season_id/standings/:id/edit' => 'season_teams#edit', :as => 'edit_standing'
  
  get 'seasons/:season_id/season_teams/:id' => 'season_teams#show', :as => 'season_season_team'
  
  post 'season_teams' => 'season_teams#create', :as => 'season_teams'
  
  get 'season_teams/new' => 'season_teams#new', :as => 'new_season_team'
  
  get 'seasons/:id/schedule' => 'matches#index', :as => 'schedule'
  
  get 'seasons/:id/playoffs' => 'matches#playoff', :as => 'playoff'
  
  get 'seasons/:season_id/schedule/match/:id' => 'matches#show', :as => 'season_match'
  
  get 'seasons/:season_id/schedule/match/:id/edit' => 'games#edit', :as => 'edit_game'
end

app/models/season_team.rb
class SeasonTeam < ActiveRecord::Base
  attr_accessible :season_id, :team_id, :sets_played, :wins, :losses, :match_played, :match_wins, :match_losses
  belongs_to :team
  belongs_to :season 
  has_many :home_matches, :foreign_key => "season_home_team_id", :class_name => "Match"
  has_many :away_matches, :foreign_key => "season_away_team_id", :class_name => "Match"
  has_many :season_team_users
  has_many :users, through: :season_team_users
  has_many :games, through: :matches

end

app/controllers/season_teams_controller.rb
class SeasonTeamsController < ApplicationController


  def standing
#   	@seaon_team = SeasonTeam.all
  	@season = Season.find(params[:id])
    @season_teams = @season.season_teams

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @season_teams }
    end
  end
  

  # GET /teams/1
  # GET /teams/1.json
  def show
  	
    @season_team = SeasonTeam.find(params[:id])
    @season = @season_team.season
    @users = @season_team.users.uniq{|user| user.id}
    @hmatch = @season_team.home_matches
    @amatch = @season_team.away_matches
    @matches = @hmatch | @amatch

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @season_team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @season_team = SeasonTeam.new
    @season_team.season = Season.find_by_id(params[:season])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @season_team }
    end
  end

  # GET /teams/1/edit
  def edit
    @season_team = SeasonTeam.find(params[:id])
  end

  # POST /teams
  # POST /teams.json
  def create
    @season_team = SeasonTeam.new(params[:season_team])

    respond_to do |format|
      if @season_team.save
        format.html { redirect_to @season_team, notice: 'Team was successfully created.' }
        format.json { render json: @season_team, status: :created, location: @season_team }
      else
        format.html { render action: "new" }
        format.json { render json: @season_team.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    @season_team = SeasonTeam.find(params[:id])

    respond_to do |format|
      if @season_team.update_attributes(params[:season_team])
        format.html { redirect_to @season_team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @season_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @season_team = SeasonTeam.find(params[:id])
    @season_team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end
end

app/views/season_teams/_form.html.erb
<%= form_for(@season_team) do |f| %>
  <% if @season_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season_team.errors.count, "error") %> prohibited this team from being saved:</h2>

      <ul>
      <% @season_team.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :season_id %><br />
    <%= f.number_field :season_id %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br />
    <%= f.number_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :sets_played %><br />
    <%= f.number_field :sets_played %>
  </div>
  <div class="field">
    <%= f.label :wins %><br />
    <%= f.number_field :wins %>
  </div>
  <div class="field">
    <%= f.label :losses %><br />
    <%= f.number_field :losses %>
  </div>
    <div class="field">
    <%= f.label :match_played %><br />
    <%= f.number_field :match_played %>
  </div>
  <div class="field">
    <%= f.label :match_wins %><br />
    <%= f.number_field :match_wins %>
  </div>
  <div class="field">
    <%= f.label :match_losses %><br />
    <%= f.number_field :match_losses %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/season_teams/edit.html.erb
<h1>Editing team</h1>

<%= render 'form' %>

<%= link_to 'Show', season_season_team_path %> |
<%= link_to 'Back', standings_path %>

app/views/season_teams/home.html.erb
<html lang="en"><head>
    <meta charset="utf-8">
    <title>League Manager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link href="/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="/assets/ico/favicon.png">
  <style type="text/css"></style></head>

  <body><div id="StayFocusd-infobar" style="display: none; top: 0px;"><img src="chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/img/eye_19x19_red.png"><span id="StayFocusd-infobar-msg"></span><span id="StayFocusd-infobar-links"><a href="#" id="StayFocusd-infobar-never-show">hide forever</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#" id="StayFocusd-infobar-hide">hide once</a></span></div>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li><%= link_to 'Home', home_url %></li>
          <li><%= link_to 'Season', seasons_url %></li>
          <li><%= link_to 'Season', contacts_url %></li>
        </ul>
        <h3 class="muted">Ultimate League experience</h3>
      </div>

      <hr>

      <div class="jumbotron">
        <h1>Serve it Up!</h1>
        <p class="lead">League Managing</p>
        <a class="btn btn-large btn-success" href="#">Enter our site</a>
      </div>

      <hr>

      <div class="row-fluid marketing">
        <div class="span6">
          <h4>Seasons</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Schedule</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="span6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Standing</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>

      <hr>

      <div class="footer">
        <p></p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="/assets/js/jquery.js"></script>
    <script src="/assets/js/bootstrap-transition.js"></script>
    <script src="/assets/js/bootstrap-alert.js"></script>
    <script src="/assets/js/bootstrap-modal.js"></script>
    <script src="/assets/js/bootstrap-dropdown.js"></script>
    <script src="/assets/js/bootstrap-scrollspy.js"></script>
    <script src="/assets/js/bootstrap-tab.js"></script>
    <script src="/assets/js/bootstrap-tooltip.js"></script>
    <script src="/assets/js/bootstrap-popover.js"></script>
    <script src="/assets/js/bootstrap-button.js"></script>
    <script src="/assets/js/bootstrap-collapse.js"></script>
    <script src="/assets/js/bootstrap-carousel.js"></script>
    <script src="/assets/js/bootstrap-typeahead.js"></script>

  

<div id="krOPPVdhx8kHsGOGRogVpjzgOnFnmwNLrqjBRq8KrpNMfRGbZO" style="display:none !important;"></div></body></html>

app/views/season_teams/new.html.erb
<h1>New SeasonTeam</h1>

<%= render 'form' %>

<!-- <%= link_to 'Back', season_teams_path %> -->

app/views/season_teams/new_app_layout_.html.erb
</html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>League Manager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link href="/assets/css/bootstrap-responsive.css" rel="stylesheet">
  




    <!-- Le styles -->


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  <style type="text/css"></style></head>

  <body><div id="StayFocusd-infobar" style="display: none; top: 0px;"><img src="chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/img/eye_19x19_red.png"><span id="StayFocusd-infobar-msg"></span><span id="StayFocusd-infobar-links"><a href="#" id="StayFocusd-infobar-never-show">hide forever</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#" id="StayFocusd-infobar-hide">hide once</a></span></div>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li><%= link_to 'Home', home_url %></li>
          <li><%= link_to 'Season', seasons_url %></li>
          <li><%= link_to 'Season', contacts_url %></li>
        </ul>
        <h3 class="muted">Ultimate League experience</h3>
      </div>

      <hr>

      <div class="jumbotron">
        <h1></h1>
        <p class="lead"></p>
        <a class="btn btn-large btn-success" href="#"></a>
      </div>

      <hr>

      <div class="row-fluid marketing">
        <div class="span6">
          <h4></h4>
          <p></p>
          <p></p>
        </div>

        <div class="span6">
          <h4></h4>
          <p></p>
          <p></p>
        </div>
        
        <div class="span6">
          <h4></h4>
          <p></p>
          <p></p>
        </div>
        
      </div>

      <hr>

      <div class="footer">
        <p></p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>

  

<div id="krOPPVdhx8kHsGOGRogVpjzgOnFnmwNLrqjBRq8KrpNMfRGbZO" style="display:none !important;"></div>
</body>
</html>

app/views/season_teams/old_application_layout.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LeagueManager" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <nav>
        <div>
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          
          <footer>
          	<% if user_signed_in? %>
          		<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
          	<% else %>
          		<li><%= link_to'Sign In', sign_up_url %></a></li>
          	<% end %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>

</html>

app/views/season_teams/show.html.erb
<html>
<head>
  <title>league Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<p id="notice"><%= notice %></p>
    
<div class="masthead">
	<ul class="nav nav-pills pull-left">
    	<li><%= link_to 'Home', season_path(@season) %></li>
        <li><%= link_to 'Standings', standings_path(@season) %></li>
        <li><%= link_to 'Schedule', schedule_path(@season) %></li>
    </ul>
</div>
      
<div class="container-wide">
	<hr>
	<div class="jumbotron">
		<h1> <%= @season_team.team.name %> </h1>
		<p class="lead">Record:(<%= @season_team.wins%>W-<%=@season_team.losses%>L)</p>
	</div>
	
	<hr>
	
	<li> Games Played: <%= @season_team.sets_played %> (<%= @season_team.wins%> Wins - <%=@season_team.losses%> Losses) </li>
	<li> Matches Played: <%= @season_team.match_played %> (<%= @season_team.match_wins%> Wins - <%=@season_team.match_losses%> Losses)</li>
	
	<div class="row-fluid marketing">


<!--
        <div class="span6">
    		<h4>Players</h4>
    		<% @users.each do |user| %>
        		<p><%= user.email %> </p>
        	<% end %>
        </div>
-->
	
        <div class="span6">
			<h4>Schedule</h4>
			<body>

				<table border="1" cellpadding="8">
					<thead>

						<th>Date</th>
						<th>Time</th>
						<th>Court</th>
						<th>Opponent</th>

					</thead>
				
				<% matches = @matches.sort_by! {|m|m.date}%>
				<% matches.each do |match| %>
					<tr>
						<td><%= match.date.strftime("%m/%d/%Y") %></td>
						<td><%= match.timeslot.name%></td>
						<td><%= match.court%></td>
						<td><%= match.display_opponent(@season_team) %></td>
						
					</tr>
				<% end %>
				
				</table>
			</body>
		</div>
	</div>

        
<%= link_to 'Back to League', season_path(@season) %>
	<hr>
</div>
</html>

app/views/season_teams/standing.html.erb
<html>

<head>
  <title>league Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<p id="notice"><%= notice %></p>
    
      <div class="masthead">
        <ul class="nav nav-pills pull-left">
        	<li><%= link_to 'Home', season_url %></li>
        	<li><%= link_to 'Standings', standings_url %></li>
        	<li><%= link_to 'Schedule', schedule_url %></li>
        </ul>
      </div>


<div class="container-wide">

	<hr>
	<div class="jumbotron">
		<h1>Standings</h1>
		<p class="lead"><%= "#{@season.name} #{@season.end.strftime('%Y')}" %></p>
	</div>
	
	<hr>
	
	<div class="row-fluid marketing">
		<div class="span12">

			<table>

				<thead>
					<tr>
						<th>Teams</th>
						<th>Games Played</th>
						<th>Game W</th>
						<th>Game L</th>
						<th>Matches Played</th>
						<th>Match W</th>
						<th>Match L</th>
						<% if user_signed_in? %>
							<th></th>
							<th></th>
						<% end %>
					</tr>
				</thead>
				
				<tbody>
				<% seasonteams = @season_teams.sort_by! {|st|[st.wins, st.match_wins]}%>
				<% seasonteams.reverse.each do |seasonteam| %>
					<tr>
          				<td><%= link_to "#{seasonteam.team.name} ", [seasonteam.season, seasonteam] %> </td>
          				<td><%= seasonteam.sets_played %></td>
          				<td><%= seasonteam.wins %></td>
          				<td><%= seasonteam.losses %></td>
          				<td><%= seasonteam.match_played %></td>
          				<td><%= seasonteam.match_wins %></td>
          				<td><%= seasonteam.match_losses %></td>
<!--           				<td><%= link_to 'Edit', edit_standing_path(seasonteam.season, seasonteam) %></td> -->
					</tr>
          		<% end %>
				</tbody>
			</table>	
		</div>
		
	</div>
	<hr>
</div>
</html>