config/routes.rb
LeagueManager::Application.routes.draw do
  
  devise_for :users

  devise_scope :user do
  	get 'sign_up' => 'devise/sessions#new'
  end

  root :to => 'seasons#index'
  
  resources :timeslots
  
  resources :matches

  resources :teams
  
  
  get 'home' => 'home#index'
  
  get 'sched' => 'matches#index'
  
  get 'standings' => 'teams#index'
  
  get 'contacts' => 'home#contact'
    
  
#   delete 'lines/:id', :controller => 'lines', :action => 'destroy', :as => 'train_line'
  
  put 'seasons/:id' => 'seasons#update'
  
  get 'seasons/:id/edit' => 'seasons#edit', :as => 'edit_season'
  
  post 'seasons' => 'seasons#create', :as => 'seasons'
  
  get 'seasons/new' => 'seasons#new', :as => 'new_season'
  
  get 'seasons' => 'seasons#index'
  
  get 'seasons/:id' => 'seasons#show', :as => 'season'
  
  put 'seasons/:season_id/season_teams/:id' => 'season_teams#update', :as => 'season_team'
  
  get 'seasons/:id/standings' => 'season_teams#standing', :as => 'standings'
  
  get 'seasons/:season_id/standings/:id/edit' => 'season_teams#edit', :as => 'edit_standing'
  
  get 'seasons/:season_id/season_teams/:id' => 'season_teams#show', :as => 'season_season_team'
  
  post 'season_teams' => 'season_teams#create', :as => 'season_teams'
  
  get 'season_teams/new' => 'season_teams#new', :as => 'new_season_team'
  
  get 'seasons/:id/schedule' => 'matches#index', :as => 'schedule'
  
  get 'seasons/:id/playoffs' => 'matches#playoff', :as => 'playoff'
  
  get 'seasons/:season_id/schedule/match/:id' => 'matches#show', :as => 'season_match'
  
  get 'seasons/:season_id/schedule/match/:id/edit' => 'games#edit', :as => 'edit_game'
end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :date, :timeslot_id, :season_home_team_id, :season_away_team_id, :court, :winner, :season_id
  
  belongs_to :season
  belongs_to :season_team 
  belongs_to :season_home_team, :foreign_key => "season_home_team_id", :class_name => "SeasonTeam"
  belongs_to :season_away_team, :foreign_key => "season_away_team_id", :class_name => "SeasonTeam"
  has_many :games
  belongs_to :timeslot
  accepts_nested_attributes_for :games
  
  def display_home_team_name
  	
  	if self.season_home_team.nil?
  	
  		home_team = "bye"
  	else
  		home_team = self.season_home_team.team.name
  	end
  	
  	home_team 
  end
  
    def display_away_team_name
  	
  	if self.season_away_team.nil?
  	
  		away_team = "bye"
  	else
  		away_team = self.season_away_team.team.name
  	end
  	
  	away_team 
  end
  
  def display_opponent(season_team)
  
  	if season_team == self.season_home_team 
  		opponent = self.display_away_team_name
  	else 
  		opponent = self.display_home_team_name
  	end
  	
  	opponent
  	
  end
  
#   def get_games
#   	games = self.games
#   	
#   end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # GET /schedules
  # GET /schedules.json
  def index
  	@season = Season.find_by_id(params[:id])
    @matches = @season.matches
#     @match = @matches.find(params[:id])
#     @seasonteams = @season.season_teams
#     @teams = @season.teams.uniq{|team| team.id}
#     @users = @season.users.uniq{|user| user.id}
    @seasons = Season.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seasons }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @match = Match.find_by_id(params[:id])
    @season = @match.season
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /schedules/1/edit
  def edit
    @match = Match.find(params[:id])
    @games = @match.games.all
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @match = Match.find(params[:id])
#     @match.update(params.require(:match_date, :match_timeslot, :season_home_team_id, :season_away_team_id))
#     redirect_to @match
    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :timeslot_id %><br />
    <%= f.number_field :timeslot_id %>
  </div>
  
  <div class="field">
    <%= f.label :season_home_team_id %><br />
    <%= f.number_field :season_home_team_id %>
  </div>
  
  <div class="field">
    <%= f.label :season_away_team_id %><br />
    <%= f.number_field :season_away_team_id %>
  </div> 
  
  <table>
  
  	<thead>
  		<th>Game</th>
  		<th> <%= @match.season_home_team.team.name %></th>
  		<th> <%= @match.season_away_team.team.name %></th>
  	</thead>
		<%= f.fields_for :games do |games_fields| %>
			  <tr>
			  	<td><%= games_fields.text_field :sequence_id %></td>
			    <td><%= games_fields.text_field :teamA_score %></td>
			    <td><%= games_fields.text_field :teamB_score %></td>
			  </tr>

		<% end %>
  
  </table>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<html>

<head>
  <title>league Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<p id="notice"><%= notice %></p>

      <div class="masthead">
        <ul class="nav nav-pills pull-left">
        	<li><%= link_to 'Home', season_url %></li>
        	<li><%= link_to 'Standings', standings_url %></li>
        	<li><%= link_to 'Schedule', schedule_url %></li>
        </ul>
      </div>


<div class="container-wide">

	<hr>
	
	<div class="jumbotron">
		<h1>Schedule</h1>
		<p class="lead"><%= "#{@season.name} #{@season.end.strftime('%Y')}" %></p>
	</div>
	
	<hr>
	<h4><%= link_to "View Playoff", playoff_url %></h4>
	<div class="row-fluid marketing">
<!-- 		<p><a id="display-past-games" href="#">Display past matches</a></p> -->
		<table border="1" cellpadding="8">
			<thead>
				<th>Date</th>
				<th>Time</th>
				<th>Court</th>
				<th>Home</th>
				<th>Away</th>
			</thead>

			<% @matches.each do |match| %>
			<tr>
<!-- 			<tr <%= match.date < DateTime.now - 1.days ? "class='done mute hide'" : "class='upcomming'" %>> -->
				<td><%= match.date.strftime("%m/%d/%Y") %>  </td>
				<td><%= match.timeslot.name%></td>
<!-- 				<td><%= match.court%></td> -->
				<td><%= link_to "#{match.court}", [match.season, match] %></td>
				<td><%= link_to "#{match.display_home_team_name} ", [match.season, match.season_home_team]%></td>
<!-- 				<td><%= match.display_home_team_name %></td> -->
				<td><%= link_to "#{match.display_away_team_name} ", [match.season, match.season_away_team]%></td>
<!-- 				<td><%= match.display_away_team_name %></td> -->
				<td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>

				<% if user_signed_in? %>
					<td><%= link_to 'Show', match %></td>
					<td><%= link_to 'Edit', edit_match_path(match) %></td>
					<td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% end %>
			</tr>
			<% end %>
		</table>
	</div>
	

</div>

</html>

<script type="text/javascript">
(function ($) {
	$(function() {
		$('#display-past-games').click(function () {
			$('.done').removeClass('hide');
			return false;
		});
		
	});
})(jQuery);

</script>

app/views/matches/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/playoff.html.erb
<html>

<head>
  <title>league Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<p id="notice"><%= notice %></p>

      <div class="masthead">
        <ul class="nav nav-pills pull-left">
        	<li><%= link_to 'Home', season_url %></li>
        	<li><%= link_to 'Standings', standings_url %></li>
        	<li><%= link_to 'Schedule', schedule_url %></li>
        </ul>
      </div>


<div class="container-wide">

	<hr>
	
	<div class="jumbotron">
		<h1>Playoffs</h1>
		
	</div>
	
	<hr>

		<div class="span10">
			<h4><%= link_to "View Regular Season Schedule", schedule_url %></h4>
			<h3>May 27, 2014</h3>
			<table>
				<thead>
					<th>Time</th>
					<th>Court 1</th>
					<th>Court 2</th>
				</thead>
				
				<tbody>
					<tr>
						<td>7:00pm</td>
						<td>(1st seed) vs (8th seed) </td>
						<td>(4th seed) vs (5th seed) </td>
					</tr>

					<tr>
						<td>8:00pm</td>
						<td>(2nd seed) vs (7th seed)</td>
						<td>(3rd seed) vs (6th seed)</td>
					</tr>

				</tbody>
			</table> 
			
			<br>
			
			<h3>June 03, 2014</h3>
			<table>
				<thead>
					<th>Time</th>
					<th>Court 1</th>
					<th>Court 2</th>
				</thead>
				
				<tbody>
					<tr>
						<td>7:00pm</td>
						<td>(1 vs 8) VS (4 vs 5) </td>
						<td>(2 vs 7) VS (3 vs 6) </td>
					</tr>

					<tr>
						<td>8:00pm</td>
						<td colspan = "2">Championship</td>
					</tr>

				</tbody>
			</table>
        </div> 
        <br>
 <div>
 <html>

app/views/matches/show.html.erb
<head>
  <title>league Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<p id="notice"><%= notice %></p>

<p>
  <b>Date</b>
  <%= @match.date.strftime("%m/%d/%Y") %>
</p>

<p>
  <b>Time</b>
  <%= @match.timeslot.name %>
</p>

<hr>
	<div class="row-fluid marketing">
        <div class="span12">
			<table>
			
			<thead>
			  <tr>
			  	<th></th>
			    <th><%= @match.season_home_team.team.name %></th>
			    <th><%= @match.season_away_team.team.name %></th>
			<!--
			    <% if user_signed_in? %>
			    	<th></th>
			    	<th></th>
			    <% end %>
			-->
			
			  </tr>
			  
			  <% @match.games.each do |g| %>
			  <tr>
			  	<td><%= g.sequence_id %></td>
			    <td><%= g.teamA_score %></td>
			    <td><%= g.teamB_score %></td>
<!-- 			    <td><%= link_to 'Edit', edit_game_path(g) %></td> -->
			  </tr>
			  <% end %>
			  
			</thead>

			 
			</table>
        </div>
	</div>




<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', schedule_path(@season) %>