config/routes.rb
LeagueManager::Application.routes.draw do
  
  devise_for :users

  devise_scope :user do
  	get 'sign_up' => 'devise/sessions#new'
  end

  root :to => 'seasons#index'
  
  resources :timeslots
  
  resources :matches

  resources :teams
  
  
  get 'home' => 'home#index'
  
  get 'sched' => 'matches#index'
  
  get 'standings' => 'teams#index'
  
  get 'contacts' => 'home#contact'
    
  
#   delete 'lines/:id', :controller => 'lines', :action => 'destroy', :as => 'train_line'
  
  put 'seasons/:id' => 'seasons#update'
  
  get 'seasons/:id/edit' => 'seasons#edit', :as => 'edit_season'
  
  post 'seasons' => 'seasons#create', :as => 'seasons'
  
  get 'seasons/new' => 'seasons#new', :as => 'new_season'
  
  get 'seasons' => 'seasons#index'
  
  get 'seasons/:id' => 'seasons#show', :as => 'season'
  
  put 'seasons/:season_id/season_teams/:id' => 'season_teams#update', :as => 'season_team'
  
  get 'seasons/:id/standings' => 'season_teams#standing', :as => 'standings'
  
  get 'seasons/:season_id/standings/:id/edit' => 'season_teams#edit', :as => 'edit_standing'
  
  get 'seasons/:season_id/season_teams/:id' => 'season_teams#show', :as => 'season_season_team'
  
  post 'season_teams' => 'season_teams#create', :as => 'season_teams'
  
  get 'season_teams/new' => 'season_teams#new', :as => 'new_season_team'
  
  get 'seasons/:id/schedule' => 'matches#index', :as => 'schedule'
  
  get 'seasons/:id/playoffs' => 'matches#playoff', :as => 'playoff'
  
  get 'seasons/:season_id/schedule/match/:id' => 'matches#show', :as => 'season_match'
  
  get 'seasons/:season_id/schedule/match/:id/edit' => 'games#edit', :as => 'edit_game'
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  attr_accessible :name, :season_id
  
  has_many :matches
  belongs_to :season
  

end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  
  def index
    @timeslots = Timeslot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timeslots }
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @timeslot = Timeslot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timeslot }
    end
  end


  def new
    @timeslot = Timeslot.new
    @timeslot.season = Season.find_by_id(params[:season])


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timeslot }
    end
  end

  def edit
    @timeslot = Timeslot.find(params[:id])
  end

 
  def create
    @timeslot = Timeslot.new(params[:timeslot])

    respond_to do |format|
      if @timeslot.save
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully created.' }
        format.json { render json: @timeslot, status: :created, location: @timeslot }
      else
        format.html { render action: "new" }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    @timeslot = Timeslot.find(params[:id])

    respond_to do |format|
      if @timeslot.update_attributes(params[:timeslot])
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @timeslot = Timeslot.find(params[:id])
    @timeslot.destroy

    respond_to do |format|
      format.html { redirect_to timeslots_url }
      format.json { head :no_content }
    end
  end
end

app/views/timeslots/_form.html.erb
<%= form_for(@timeslot) do |f| %>
  <% if @timeslot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timeslot.errors.count, "error") %> prohibited this timeslot from being saved:</h2>

      <ul>
      <% @timeslot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= f.label :season_id %><br />
    <%= f.collection_select :season_id, Season.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

 

app/views/timeslots/edit.html.erb
<h1>Editing timeslot</h1>

<%= render 'form' %>

<%= link_to 'Show', @timeslot %> |
<%= link_to 'Back', timeslots_path %>

app/views/timeslots/index.html.erb
<html>

<head>
  <title>league Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>


<h1>timeslots</h1>

<table>

<thead>
  <tr>
    <th>Season</th>
    <th>Timeslot</th>
  </tr>
</thead>

<tbody>
<% @timeslots.each do |timeslot| %>
  <tr>
  	<td><%= timeslot.season_id %></td>
    <td><%= timeslot.name %></td>
    	<td><%= link_to 'Edit', edit_timeslot_path(timeslot) %></td>
    	<td><%= link_to 'Destroy', timeslot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
 
</table>

<br />
		<%= link_to 'New Timeslot', new_timeslot_path %>

</html>

app/views/timeslots/new.html.erb
<h1>New timeslot</h1>

<%= render 'form' %>

<%= link_to 'Back', timeslots_path %>

app/views/timeslots/show.html.erb
<head>
  <title>league Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<p id="notice"><%= notice %></p>


<div class="container-wide">
	<hr>
	<div class="jumbotron">
		<h1> Season <%= @timeslot.season_id %>  </h1>
		<p>Timeslot <%= @timeslot.name %> </p>
	</div>

	<hr>
<div>

        
<%= link_to 'Edit', edit_team_path(@timeslot) %> |
<%= link_to 'Back to League', seasons_path %>
	<hr>
</div>