config/routes.rb
LeagueManager::Application.routes.draw do
  
  devise_for :users

  devise_scope :user do
  	get 'sign_up' => 'devise/sessions#new'
  end

  root :to => 'seasons#index'
  
  resources :timeslots
  
  resources :matches

  resources :teams
  
  
  get 'home' => 'home#index'
  
  get 'sched' => 'matches#index'
  
  get 'standings' => 'teams#index'
  
  get 'contacts' => 'home#contact'
    
  
#   delete 'lines/:id', :controller => 'lines', :action => 'destroy', :as => 'train_line'
  
  put 'seasons/:id' => 'seasons#update'
  
  get 'seasons/:id/edit' => 'seasons#edit', :as => 'edit_season'
  
  post 'seasons' => 'seasons#create', :as => 'seasons'
  
  get 'seasons/new' => 'seasons#new', :as => 'new_season'
  
  get 'seasons' => 'seasons#index'
  
  get 'seasons/:id' => 'seasons#show', :as => 'season'
  
  put 'seasons/:season_id/season_teams/:id' => 'season_teams#update', :as => 'season_team'
  
  get 'seasons/:id/standings' => 'season_teams#standing', :as => 'standings'
  
  get 'seasons/:season_id/standings/:id/edit' => 'season_teams#edit', :as => 'edit_standing'
  
  get 'seasons/:season_id/season_teams/:id' => 'season_teams#show', :as => 'season_season_team'
  
  post 'season_teams' => 'season_teams#create', :as => 'season_teams'
  
  get 'season_teams/new' => 'season_teams#new', :as => 'new_season_team'
  
  get 'seasons/:id/schedule' => 'matches#index', :as => 'schedule'
  
  get 'seasons/:id/playoffs' => 'matches#playoff', :as => 'playoff'
  
  get 'seasons/:season_id/schedule/match/:id' => 'matches#show', :as => 'season_match'
  
  get 'seasons/:season_id/schedule/match/:id/edit' => 'games#edit', :as => 'edit_game'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div>
                <div>
                    <ul>
                        <div class="container-narrow">
	                        <div class="masthead">
		                        <ul class="nav nav-pills pull-right">
			                        <li><%= link_to 'Home', home_url %></li>
			                        <li><%= link_to 'Season', seasons_url %></li>
			                        <li><%= link_to 'Contacts', contacts_url %></li>
			                    </ul>
	                        	<h3 class="muted">Ultimate League experience</h3>
	                        </div>
                        </div>
<!--
                        <li><%= link_to "Home", home_url, :class => 'brand' %></li>
                        
                        <li><%= link_to 'Schedule', sched_url %></li>
                        <li><%= link_to 'Teams', standings_url %></li>
                        <li><%= link_to 'Contacts', contacts_url %></li>
-->
<!--
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                          <ul id="dropdown-menu" class="dropdown-menu">
                            <li><a href="#">Dropdown 1</a></li>
                            <li><a href="#">Dropdown 2</a></li>
                            <li><a href="#">Dropdown 3</a></li>
                            <li class="divider"></li>
                            <li class="nav-header">Nav header</li>
                            <li><a href="#">Dropdown 4</a></li>
                            <li><a href="#">Dropdown 5</a></li>
                          </ul>
                        </li>
-->
                    </ul>
                </div><!-- /.nav-collapse
            </div><!--/.container-->
        </div><!-- /navbar-inner -->
    </div>
</header>
-->


<!--
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>League Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
      <link href="/assets/css/bootstrap.css" rel="stylesheet">
  <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
/*         background-image: url("/assets/debut_dark.png"); */
       	background-color: hsl()
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link href="/assets/css/bootstrap-responsive.css" rel="stylesheet">
</head>
<body>
      <div class="masthead">
        <ul class="nav nav-pills pull-right">
<!--           <li><%= link_to 'Seasons', seasons_url %></li> -->
<!--           <li><%= link_to 'Contacts', contacts_url %></li> -->
        </ul>
<!--         <h3 class="muted"><%=link_to 'Volleyball', home_url %></h3> -->
        <h3 class="muted">Volleyball</h3>
      </div>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

<%= yield %>

<!--

    <footer>
    	<% if user_signed_in? %>
        	<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
        	<li><%= link_to'Sign In', sign_up_url %></a></li>
        <% end %>
    </footer>
-->
</body>
</html>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    
    
    <!--
<script src="/assets/js/bootstrap-transition.js"></script>
    <script src="/assets/js/bootstrap-alert.js"></script>
    <script src="/assets/js/bootstrap-modal.js"></script>
    <script src="/assets/js/bootstrap-dropdown.js"></script>
    <script src="/assets/js/bootstrap-scrollspy.js"></script>
    <script src="/assets/js/bootstrap-tab.js"></script>
    <script src="/assets/js/bootstrap-tooltip.js"></script>
    <script src="/assets/js/bootstrap-popover.js"></script>
    <script src="/assets/js/bootstrap-button.js"></script>
    <script src="/assets/js/bootstrap-collapse.js"></script>
    <script src="/assets/js/bootstrap-carousel.js"></script>
    <script src="/assets/js/bootstrap-typeahead.js"></script>
-->